/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dev.supersam.fridaSource;

public final class FridaScope {
  public final static FridaScope FRIDA_SCOPE_MINIMAL = new FridaScope("FRIDA_SCOPE_MINIMAL");
  public final static FridaScope FRIDA_SCOPE_METADATA = new FridaScope("FRIDA_SCOPE_METADATA");
  public final static FridaScope FRIDA_SCOPE_FULL = new FridaScope("FRIDA_SCOPE_FULL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FridaScope swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FridaScope.class + " with value " + swigValue);
  }

  private FridaScope(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FridaScope(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FridaScope(String swigName, FridaScope swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FridaScope[] swigValues = { FRIDA_SCOPE_MINIMAL, FRIDA_SCOPE_METADATA, FRIDA_SCOPE_FULL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

