/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dev.supersam.fridaSource;

public class frida {
  public static void frida_init() {
    fridaJNI.frida_init();
  }

  public static void frida_shutdown() {
    fridaJNI.frida_shutdown();
  }

  public static SWIGTYPE_p__FridaDeviceManager frida_device_manager_new() {
    long cPtr = fridaJNI.frida_device_manager_new();
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaDeviceManager(cPtr, false);
  }

  public static SWIGTYPE_p__FridaDevice frida_device_manager_get_device_by_id_sync(SWIGTYPE_p__FridaDeviceManager self, String id, int timeout) {
    long cPtr = fridaJNI.frida_device_manager_get_device_by_id_sync(SWIGTYPE_p__FridaDeviceManager.getCPtr(self), id, timeout);
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaDevice(cPtr, false);
  }

  public static SWIGTYPE_p__FridaDeviceList frida_device_manager_enumerate_devices_sync(SWIGTYPE_p__FridaDeviceManager self) {
    long cPtr = fridaJNI.frida_device_manager_enumerate_devices_sync(SWIGTYPE_p__FridaDeviceManager.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaDeviceList(cPtr, false);
  }

  public static int frida_device_list_size(SWIGTYPE_p__FridaDeviceList self) {
    return fridaJNI.frida_device_list_size(SWIGTYPE_p__FridaDeviceList.getCPtr(self));
  }

  public static SWIGTYPE_p__FridaDevice frida_device_list_get(SWIGTYPE_p__FridaDeviceList self, int index) {
    long cPtr = fridaJNI.frida_device_list_get(SWIGTYPE_p__FridaDeviceList.getCPtr(self), index);
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaDevice(cPtr, false);
  }

  public static String frida_device_get_id(SWIGTYPE_p__FridaDevice self) {
    return fridaJNI.frida_device_get_id(SWIGTYPE_p__FridaDevice.getCPtr(self));
  }

  public static String frida_device_get_name(SWIGTYPE_p__FridaDevice self) {
    return fridaJNI.frida_device_get_name(SWIGTYPE_p__FridaDevice.getCPtr(self));
  }

  public static FridaDeviceType frida_device_get_dtype(SWIGTYPE_p__FridaDevice self) {
    return FridaDeviceType.swigToEnum(fridaJNI.frida_device_get_dtype(SWIGTYPE_p__FridaDevice.getCPtr(self)));
  }

  public static void frida_unref(SWIGTYPE_p_void obj) {
    fridaJNI.frida_unref(SWIGTYPE_p_void.getCPtr(obj));
  }

  public static SWIGTYPE_p__FridaApplicationList frida_device_enumerate_applications_sync(SWIGTYPE_p__FridaDevice self, SWIGTYPE_p__FridaApplicationQueryOptions options) {
    long cPtr = fridaJNI.frida_device_enumerate_applications_sync(SWIGTYPE_p__FridaDevice.getCPtr(self), SWIGTYPE_p__FridaApplicationQueryOptions.getCPtr(options));
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaApplicationList(cPtr, false);
  }

  public static int frida_application_list_size(SWIGTYPE_p__FridaApplicationList self) {
    return fridaJNI.frida_application_list_size(SWIGTYPE_p__FridaApplicationList.getCPtr(self));
  }

  public static SWIGTYPE_p__FridaApplication frida_application_list_get(SWIGTYPE_p__FridaApplicationList self, int index) {
    long cPtr = fridaJNI.frida_application_list_get(SWIGTYPE_p__FridaApplicationList.getCPtr(self), index);
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaApplication(cPtr, false);
  }

  public static String frida_application_get_identifier(SWIGTYPE_p__FridaApplication self) {
    return fridaJNI.frida_application_get_identifier(SWIGTYPE_p__FridaApplication.getCPtr(self));
  }

  public static String frida_application_get_name(SWIGTYPE_p__FridaApplication self) {
    return fridaJNI.frida_application_get_name(SWIGTYPE_p__FridaApplication.getCPtr(self));
  }

  public static long frida_application_get_pid(SWIGTYPE_p__FridaApplication self) {
    return fridaJNI.frida_application_get_pid(SWIGTYPE_p__FridaApplication.getCPtr(self));
  }

  public static SWIGTYPE_p_GHashTable frida_application_get_parameters(SWIGTYPE_p__FridaApplication self) {
    long cPtr = fridaJNI.frida_application_get_parameters(SWIGTYPE_p__FridaApplication.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_GHashTable(cPtr, false);
  }

  public static SWIGTYPE_p__FridaApplicationQueryOptions frida_application_query_options_new() {
    long cPtr = fridaJNI.frida_application_query_options_new();
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaApplicationQueryOptions(cPtr, false);
  }

  public static FridaScope frida_application_query_options_get_scope(SWIGTYPE_p__FridaApplicationQueryOptions self) {
    return FridaScope.swigToEnum(fridaJNI.frida_application_query_options_get_scope(SWIGTYPE_p__FridaApplicationQueryOptions.getCPtr(self)));
  }

  public static void frida_application_query_options_set_scope(SWIGTYPE_p__FridaApplicationQueryOptions self, FridaScope value) {
    fridaJNI.frida_application_query_options_set_scope(SWIGTYPE_p__FridaApplicationQueryOptions.getCPtr(self), value.swigValue());
  }

  public static void frida_application_query_options_select_identifier(SWIGTYPE_p__FridaApplicationQueryOptions self, String identifier) {
    fridaJNI.frida_application_query_options_select_identifier(SWIGTYPE_p__FridaApplicationQueryOptions.getCPtr(self), identifier);
  }

  public static SWIGTYPE_p_gboolean frida_application_query_options_has_selected_identifiers(SWIGTYPE_p__FridaApplicationQueryOptions self) {
    return new SWIGTYPE_p_gboolean(fridaJNI.frida_application_query_options_has_selected_identifiers(SWIGTYPE_p__FridaApplicationQueryOptions.getCPtr(self)), true);
  }

  public static void frida_application_query_options_enumerate_selected_identifiers(SWIGTYPE_p__FridaApplicationQueryOptions self, SWIGTYPE_p_GFunc func, SWIGTYPE_p_void user_data) {
    fridaJNI.frida_application_query_options_enumerate_selected_identifiers(SWIGTYPE_p__FridaApplicationQueryOptions.getCPtr(self), SWIGTYPE_p_GFunc.getCPtr(func), SWIGTYPE_p_void.getCPtr(user_data));
  }

  public static SWIGTYPE_p__FridaProcessList frida_device_enumerate_processes_sync(SWIGTYPE_p__FridaDevice self, SWIGTYPE_p_FridaProcessQueryOptions options) {
    long cPtr = fridaJNI.frida_device_enumerate_processes_sync(SWIGTYPE_p__FridaDevice.getCPtr(self), SWIGTYPE_p_FridaProcessQueryOptions.getCPtr(options));
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaProcessList(cPtr, false);
  }

  public static int frida_process_list_size(SWIGTYPE_p__FridaProcessList self) {
    return fridaJNI.frida_process_list_size(SWIGTYPE_p__FridaProcessList.getCPtr(self));
  }

  public static SWIGTYPE_p__FridaProcess frida_process_list_get(SWIGTYPE_p__FridaProcessList self, int index) {
    long cPtr = fridaJNI.frida_process_list_get(SWIGTYPE_p__FridaProcessList.getCPtr(self), index);
    return (cPtr == 0) ? null : new SWIGTYPE_p__FridaProcess(cPtr, false);
  }

  public static long frida_process_get_pid(SWIGTYPE_p__FridaProcess self) {
    return fridaJNI.frida_process_get_pid(SWIGTYPE_p__FridaProcess.getCPtr(self));
  }

  public static String frida_process_get_name(SWIGTYPE_p__FridaProcess self) {
    return fridaJNI.frida_process_get_name(SWIGTYPE_p__FridaProcess.getCPtr(self));
  }

}
